using System;

namespace CraftyRacoon.GitSubmoduleBootstrap.Editor
{
    internal static class GitSubmoduleBootstrapScriptGenerator
    {
        internal const string GeneratedFileName = "Initialize Submodules.cmd";

        internal static string BuildScriptContent(string unityProjectRelativePath)
        {
            string normalizedUnityProjectRelativePath = string.IsNullOrWhiteSpace(unityProjectRelativePath) ? "." : unityProjectRelativePath.Replace('\\', '/');
            string unityProjectLockPath = normalizedUnityProjectRelativePath == "." ? "Temp\\UnityLockfile" : normalizedUnityProjectRelativePath.Replace('/', '\\') + "\\Temp\\UnityLockfile";
            string[] lines =
            {
                "@echo off",
                "setlocal EnableExtensions DisableDelayedExpansion",
                "title Git Submodule Initialization",
                "",
                "pushd \"%~dp0\" >nul || (",
                "    echo [Git Submodules] ERROR: Could not enter the project root.",
                "    pause",
                "    exit /b 1",
                ")",
                "",
                "echo [Git Submodules] Repository root: %CD%",
                "echo.",
                "",
                "git rev-parse --show-toplevel >nul 2>nul",
                "if errorlevel 1 (",
                "    echo [Git Submodules] ERROR: This script must be located in a Git working tree.",
                "    goto :fail",
                ")",
                "",
                "if not exist \".git\" (",
                "    echo [Git Submodules] ERROR: No .git metadata was found.",
                "    echo Clone the repository before running this script.",
                "    goto :fail",
                ")",
                "",
                "if not exist \".gitmodules\" (",
                "    echo [Git Submodules] ERROR: No .gitmodules file was found.",
                "    goto :fail",
                ")",
                "",
                "where git.exe >nul 2>nul",
                "if errorlevel 1 (",
                "    echo [Git Submodules] ERROR: git.exe was not found on PATH.",
                "    goto :fail",
                ")",
                "",

                "if exist \"" + unityProjectLockPath + "\" ("
                "    where powershell.exe >nul 2>nul",
                "    if errorlevel 1 (",
                "        echo [Git Submodules] ERROR: PowerShell is required to verify the Unity project lock.",
                "        goto :fail",
                "    )",
                "",
                "    powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command \"$p = Join-Path (Get-Location) '" + unityProjectLockPath.Replace("\\", "\\\\") + "'; try { $s = [System.IO.File]::Open($p, [System.IO.FileMode]::Open, [System.IO.FileAccess]::ReadWrite, [System.IO.FileShare]::None); $s.Dispose(); exit 0 } catch { exit 1 }\"",
                "    if errorlevel 1 (",
                "        echo [Git Submodules] ERROR: This Unity project is currently open.",
                "        echo Close Unity completely, then run this script again.",
                "        goto :fail",
                "    )",
                ")",
                "",
                "git status --porcelain=v1 -- \".gitmodules\" | findstr . >nul",
                "if not errorlevel 1 (",
                "    echo [Git Submodules] ERROR: .gitmodules has local modifications.",
                "    echo Commit or revert it before initializing dependencies.",
                "    goto :fail",
                ")",
                "",
                "echo [Git Submodules] Verifying parent HEAD submodule pointers...",
                "for /f \"tokens=1,*\" %%A in ('git config --file \".gitmodules\" --get-regexp \"path$\"') do (",
                "    git diff --cached --quiet HEAD -- \"%%B\"",
                "    if errorlevel 2 (",
                "        echo [Git Submodules] ERROR: Could not verify the staged submodule pointer for %%B.",
                "        goto :fail",
                "    )",
                "    if errorlevel 1 (",
                "        echo [Git Submodules] ERROR: Staged submodule pointer differs from the parent HEAD for %%B.",
                "        echo Commit or unstage the pointer change before initializing dependencies.",
                "        goto :fail",
                "    )",
                ")",
                "",
                "git submodule status >nul 2>nul",
                "if errorlevel 1 (",
                "    echo [Git Submodules] ERROR: Could not inspect submodule status.",
                "    goto :fail",
                ")",
                "",
                "git submodule status | findstr /b /c:\"-\" >nul",
                "if errorlevel 1 (",
                "    echo [Git Submodules] No missing top-level submodules were found.",
                "    echo Initialization is not required.",
                "    goto :success",
                ")",
                "",
                "git submodule status | findstr /b /c:\" \" /c:\"+\" /c:\"U\" >nul",
                "if not errorlevel 1 (",
                "    echo [Git Submodules] ERROR: The repository has a mixed submodule state.",
                "    echo Some top-level submodules are initialized while others are missing.",
                "    echo Use Unity Tools ^> Git Submodules ^> Update Now, or resolve the state manually.",
                "    goto :fail",
                ")",
                "",
                "echo [Git Submodules] Initializing all submodules recursively...",
                "git submodule update --init --recursive",
                "if errorlevel 1 (",
                "    echo [Git Submodules] ERROR: git submodule update failed.",
                "    goto :fail",
                ")",
                "",
                "git submodule status --recursive | findstr /b /c:\"-\" /c:\"+\" /c:\"U\" >nul",
                "if not errorlevel 1 (",
                "    echo [Git Submodules] ERROR: Verification found an unresolved submodule state.",
                "    goto :fail",
                ")",
                "",
                "echo [Git Submodules] Initialization completed successfully.",
                "",
                ":success",
                "echo.",
                "echo You can now open the project in Unity.",
                "popd",
                "pause",
                "exit /b 0",
                "",
                ":fail",
                "echo.",
                "echo [Git Submodules] Initialization was not completed. No forced Git operation was used.",
                "popd",
                "pause",
                "exit /b 1"
            };

            return string.Join("\r\n", lines) + "\r\n";
        }

    }
}
